---
title: "Assignment 3 Submission"
author: "Abdul Abad"
date: "October 10, 2018"
output: html_document
---
#Part 1

```{r}
getwd()
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
K1 <- read.csv("Class_Motivation.csv", header = TRUE)
```

```{r}

K2 <- dplyr::select(K1, 2:6)
```

```{r}
K3 <- na.omit(K2)
```

```{r}

K3 <- scale(K3)
```

```{r}

fit <- kmeans(K3, 2)

```

```{r}
K4 <- data.frame(K3, fit$cluster)
```

```{r}

names(K4) <- c("1", "2", "3", "4", "5", "cluster")

```

```{r}
K5 <- tidyr::gather(K4, "week", "motivation", 1:5)
```

```{r}
K6 <- K5 %>% group_by(week, cluster)
K6 <- summarise(K6, avg = mean(motivation))
```

```{r}
K6$week <- as.numeric(K6$week)
K6$cluster <- as.factor(K6$cluster)
```

```{r}
K7 <- dplyr::count(K4, cluster)
```

#Part 2

```{r}
library(tidyverse)
M1 <- read.csv("HUDK405018-cluster.csv", header = TRUE)
#Create a dataframe that only includes the surevy questions about hours
M2 <- M1[3:47, 20:26]
# Deal with missing values now
# Convert the blank cells to NAs and convert all columns to numeric
M2[M2==""] <- NA
M2 <- M2 %>% mutate_all(funs(as.numeric(levels(.))[.]))
#Recode as zero - but missing is not the same as recording zero hours
M2[is.na(M2)] <- 0
#Generate clusters for survey questions
fit2 <- kmeans(M2, 3)
#Create a dataframe that only includes location data
L1 <- M1[3:47, 18:19]
L1 <- unite(L1, place, Q1_1, Q1_2, sep = ",")
#Request lattitude and longitude from Google Maps API
library(ggmap)
L2 <- geocode(as.character(L1$place), output = "latlon", source = "dsk")
#Generate clusters for lat/lon
fit3 <- kmeans(L2, 2)

```

#Part 3

```{r}
library(vcd)
P1 <- structable(fit2$cluster ~ fit3$cluster)
mosaic(P1, shade=TRUE, legend=TRUE) 
#This shows how much overlap there are between the groups of clusters

#plot figure in file
pdf(file="Rplot.png")
plot(fit2$cluster ~ fit3$cluster)
dev.off()
```